server:
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: pisces-lfs
  profiles:
    active: '@spring.active@'
