spring:
  boot:
    admin:
      client:
        # SpringBoot Admin 服务端地址
        url: http://127.0.0.1:27777
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/lfs?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: postgres
      password: 666666
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  # JPA相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    # formatSQL
    properties:
      hibernate:
        format_sql: true

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: pisces-lfs
  # JWT的超时时间 (60*60*24*7)
  expiration: 604800
  # JWT负载头
  tokenHead: 'Bearer '

# OpenApi 配置
springdoc:
  swagger-ui:
    # 文档访问路径
    path: "/swagger-ui.html"
  packages-to-scan: com.besscroft.lfs
  api-docs:
    # 是否开启
    enabled: true

whitelist:
  urls: #配置白名单路径
    - "/**/*.js"
    - "/**/*.css"
    - "/**/*.png"
    - "/**/*.ico"
    - "/swagger-ui.html"
    - "/swagger-ui/index.html"
    - "/v3/**"
    - "/actuator/**"
    - "/druid/**"
    - "/user/login"
    - "/user/logout"
    - "/actuator/**"

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 监控项配置
        include: info, health
  endpoint:
    health:
      # 开启显示全部细节
      show-details: always
    shutdown:
      # 启用接口关闭 SpringBoot
      enabled: false

# 日志文件地址（提供给程序读取的地址，输出地址请在 log4j2.xml 配置）
logging:
  file:
    name: logs/${spring.application.name}/info.log
