name: "Java CI with Multi-arch Docker Image"

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: Running Compile Java Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push admin
        id: docker_build_admin
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/jar/lfs-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lfs-admin:latest
      - name: Build and push monitor
        id: docker_build_monitor
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.github/docker/jar/lfs-monitor/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lfs-monitor:latest
